name: ai-news-websearch

on:
  schedule:
    # Autour de minuit Europe/Paris toute l'année
    - cron: "0 22 * * *"   # ≈ 00:00 Paris (été)
    - cron: "0 23 * * *"   # ≈ 00:00 Paris (hiver)
  workflow_dispatch: {}

permissions:
  contents: read

concurrency:
  group: ai-news-websearch
  cancel-in-progress: false

jobs:
  run-digest:
    runs-on: ubuntu-latest
    timeout-minutes: 15

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Cache pip
        uses: actions/cache@v4
        with:
          path: ~/.cache/pip
          key: pip-${{ runner.os }}-${{ hashFiles('requirements.txt') }}
          restore-keys: |
            pip-${{ runner.os }}-

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Show versions (debug)
        run: |
          python --version
          pip freeze | sed -n '1,120p'

      - name: Run AI News (web search → Discord embeds)
        env:
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
          DISCORD_WEBHOOK_URL: ${{ secrets.DISCORD_WEBHOOK_URL }}
          LOCALE: "fr-FR"
          SOURCE_LANGS: "fr,en"       # << FR + EN
          TIMEZONE: "Europe/Paris"
          HOURS: "24"
          MODEL: "gpt-4.1-mini"       # possible: gpt-4.1
          EMBED_COLOR: "5793266"      # bleu
        run: |
          python veille.py
