name: veille-ia-websearch

on:
  schedule:
    # Minuit Europe/Paris toute l'année (été ≈ 22:00 UTC, hiver ≈ 23:00 UTC)
    - cron: "0 22 * * *"
    - cron: "0 23 * * *"
  workflow_dispatch: {}

permissions:
  contents: read

concurrency:
  group: veille-ia-websearch
  cancel-in-progress: false

jobs:
  run-veille:
    runs-on: ubuntu-latest
    timeout-minutes: 15

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Cache pip
        uses: actions/cache@v4
        with:
          path: ~/.cache/pip
          key: >-
            pip-${{ runner.os }}-${{ hashFiles('requirements.txt') }}
          restore-keys: |
            pip-${{ runner.os }}-

      - name: Install dependencies (from requirements.txt)
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Show versions (debug)
        run: |
          python --version
          pip freeze | sed -n '1,120p'

      - name: Run veille IA (web search + Discord embeds)
        env:
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
          DISCORD_WEBHOOK_URL: ${{ secrets.DISCORD_WEBHOOK_URL }}
          LOCALE: "fr-FR"
          TIMEZONE: "Europe/Paris"
          HOURS: "24"
          MODEL: "gpt-4.1-mini"     # tu peux passer à gpt-4.1
          EMBED_COLOR: "5793266"    # 0x5865F2 en décimal
        run: |
          python veille.py
